// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns the version of the native Swar core.
String getCoreVersion() =>
    RustLib.instance.api.crateApiDiagnosticsGetCoreVersion();

/// Emits a short counter stream from a Rust worker thread.
Stream<int> streamDemoEvents() =>
    RustLib.instance.api.crateApiDiagnosticsStreamDemoEvents();
