// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `complete_coordinator_session`, `emit_transition`, `event_kind_for_state`, `fail_start`, `finish_capture`, `is_builtin_microphone_name`, `monotonic_timestamp_ms`, `release_recording_reservation`, `resample_linear`, `select_input_device`, `spawn_preview_worker`, `stop_preview`, `take_capture`, `transcript_contains_speech`, `transition_capture`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveCapture`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Lists the audio inputs visible to CoreAudio/WASAPI through CPAL.
Future<List<MicrophoneDevice>> listMicrophones() =>
    RustLib.instance.api.crateApiDictationListMicrophones();

/// Begins a single native recording session. Raw PCM remains in Rust.
Stream<DictationEvent> startDictationSession({
  required DictationSessionConfig config,
}) =>
    RustLib.instance.api.crateApiDictationStartDictationSession(config: config);

/// Stops capture, transcribes locally with whisper.cpp, cleans, inserts, and persists.
Future<DictationCompletion> finishDictationSession({
  required String sessionId,
}) => RustLib.instance.api.crateApiDictationFinishDictationSession(
  sessionId: sessionId,
);

/// Cancels the active capture and discards all PCM without writing history.
Future<void> cancelDictationSession({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiDictationCancelDictationSession(sessionId: sessionId);

bool offlineModelIsReady({required String modelPath}) => RustLib.instance.api
    .crateApiDictationOfflineModelIsReady(modelPath: modelPath);

/// Loads the selected model on the dedicated ASR worker before the first dictation.
Future<bool> prepareDictationEngine({required String modelPath}) => RustLib
    .instance
    .api
    .crateApiDictationPrepareDictationEngine(modelPath: modelPath);

/// Releases the warm model without stopping the dedicated ASR worker.
Future<void> releaseDictationEngine() =>
    RustLib.instance.api.crateApiDictationReleaseDictationEngine();

class DictationCompletion {
  final String sessionId;
  final String rawText;
  final String finalText;
  final BigInt audioDurationMs;
  final BigInt processingDurationMs;
  final String insertionStatus;
  final String insertionMethod;

  const DictationCompletion({
    required this.sessionId,
    required this.rawText,
    required this.finalText,
    required this.audioDurationMs,
    required this.processingDurationMs,
    required this.insertionStatus,
    required this.insertionMethod,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      rawText.hashCode ^
      finalText.hashCode ^
      audioDurationMs.hashCode ^
      processingDurationMs.hashCode ^
      insertionStatus.hashCode ^
      insertionMethod.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictationCompletion &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          rawText == other.rawText &&
          finalText == other.finalText &&
          audioDurationMs == other.audioDurationMs &&
          processingDurationMs == other.processingDurationMs &&
          insertionStatus == other.insertionStatus &&
          insertionMethod == other.insertionMethod;
}

class DictationEvent {
  final String sessionId;
  final DictationEventKind kind;
  final double? audioLevel;
  final String? message;
  final BigInt timestampMs;
  final DictationLifecycleState previousState;
  final DictationLifecycleState currentState;
  final String reason;
  final String? partialText;

  const DictationEvent({
    required this.sessionId,
    required this.kind,
    this.audioLevel,
    this.message,
    required this.timestampMs,
    required this.previousState,
    required this.currentState,
    required this.reason,
    this.partialText,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      kind.hashCode ^
      audioLevel.hashCode ^
      message.hashCode ^
      timestampMs.hashCode ^
      previousState.hashCode ^
      currentState.hashCode ^
      reason.hashCode ^
      partialText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictationEvent &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          kind == other.kind &&
          audioLevel == other.audioLevel &&
          message == other.message &&
          timestampMs == other.timestampMs &&
          previousState == other.previousState &&
          currentState == other.currentState &&
          reason == other.reason &&
          partialText == other.partialText;
}

enum DictationEventKind {
  stateChanged,
  preparing,
  recording,
  audioLevel,
  finalising,
  cancelled,
  failed,
  partialTranscript,
}

enum DictationLifecycleState {
  idle,
  preparing,
  recording,
  finalising,
  transcribing,
  cleaning,
  enhancing,
  inserting,
  copiedFallback,
  completed,
  cancelled,
  failed,
}

class DictationSessionConfig {
  final String modelPath;
  final String microphoneId;
  final String language;
  final String writingMode;
  final String sourceApplication;
  final bool pasteAutomatically;
  final bool restoreClipboard;
  final int maximumSeconds;
  final bool enableLivePreview;

  const DictationSessionConfig({
    required this.modelPath,
    required this.microphoneId,
    required this.language,
    required this.writingMode,
    required this.sourceApplication,
    required this.pasteAutomatically,
    required this.restoreClipboard,
    required this.maximumSeconds,
    required this.enableLivePreview,
  });

  @override
  int get hashCode =>
      modelPath.hashCode ^
      microphoneId.hashCode ^
      language.hashCode ^
      writingMode.hashCode ^
      sourceApplication.hashCode ^
      pasteAutomatically.hashCode ^
      restoreClipboard.hashCode ^
      maximumSeconds.hashCode ^
      enableLivePreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictationSessionConfig &&
          runtimeType == other.runtimeType &&
          modelPath == other.modelPath &&
          microphoneId == other.microphoneId &&
          language == other.language &&
          writingMode == other.writingMode &&
          sourceApplication == other.sourceApplication &&
          pasteAutomatically == other.pasteAutomatically &&
          restoreClipboard == other.restoreClipboard &&
          maximumSeconds == other.maximumSeconds &&
          enableLivePreview == other.enableLivePreview;
}

class MicrophoneDevice {
  final String id;
  final String name;
  final bool isDefault;
  final bool isBuiltIn;

  const MicrophoneDevice({
    required this.id,
    required this.name,
    required this.isDefault,
    required this.isBuiltIn,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ isDefault.hashCode ^ isBuiltIn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MicrophoneDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault &&
          isBuiltIn == other.isBuiltIn;
}
