// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Initializes Swar's private SQLite store under the OS application-support directory.
Future<String> initializeLocalStore() =>
    RustLib.instance.api.crateApiHistoryInitializeLocalStore();

/// Returns one bounded history page. Search is executed by SQLite FTS, never in Dart.
Future<HistoryPage> loadHistoryPage({
  required String searchText,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiHistoryLoadHistoryPage(
  searchText: searchText,
  offset: offset,
  limit: limit,
);

/// Returns pre-aggregated local insights without exposing transcript text.
Future<InsightsSnapshot> loadInsightsSnapshot() =>
    RustLib.instance.api.crateApiHistoryLoadInsightsSnapshot();

/// Deletes local history and metrics. Model files and personal settings are untouched.
Future<void> clearLocalHistory() =>
    RustLib.instance.api.crateApiHistoryClearLocalHistory();

/// Applies an explicit user correction and optionally feeds the local learning
/// loop. The original audio is never retained.
Future<bool> correctDictation({
  required String id,
  required String correctedText,
  required bool learningOptedIn,
}) => RustLib.instance.api.crateApiHistoryCorrectDictation(
  id: id,
  correctedText: correctedText,
  learningOptedIn: learningOptedIn,
);

/// One application's share of dictations, for the "Where you dictate" card.
class AppUsage {
  final String name;
  final BigInt count;

  const AppUsage({required this.name, required this.count});

  static Future<AppUsage> default_() =>
      RustLib.instance.api.crateApiHistoryAppUsageDefault();

  @override
  int get hashCode => name.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppUsage &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          count == other.count;
}

class HistoryPage {
  final int totalCount;
  final List<StoredDictation> records;

  const HistoryPage({required this.totalCount, required this.records});

  @override
  int get hashCode => totalCount.hashCode ^ records.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPage &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          records == other.records;
}

class InsightsSnapshot {
  final BigInt totalWords;
  final BigInt totalDictations;
  final BigInt totalSpeechDurationMs;
  final double averageWordsPerMinute;
  final int currentStreakDays;
  final int longestStreakDays;

  /// Words in dictations the user later edited (a proxy for "words corrected").
  final BigInt wordsCorrected;

  /// Sum of custom-vocabulary use counts ("from your dictionary").
  final BigInt dictionaryHits;

  /// Language of the transcript inferred from its script: pure Latin -> English,
  /// pure Devanagari -> Hindi, mixed -> Hinglish. Counts of dictations per class.
  final BigInt languageEnglish;
  final BigInt languageHindi;
  final BigInt languageHinglish;

  /// Top applications by dictation count (already bounded), plus the total
  /// number of distinct applications seen.
  final List<AppUsage> appUsage;
  final BigInt distinctAppCount;

  /// Per-day dictation counts for the streak heatmap, oldest first, ending today.
  final Uint32List dailyActivity;

  const InsightsSnapshot({
    required this.totalWords,
    required this.totalDictations,
    required this.totalSpeechDurationMs,
    required this.averageWordsPerMinute,
    required this.currentStreakDays,
    required this.longestStreakDays,
    required this.wordsCorrected,
    required this.dictionaryHits,
    required this.languageEnglish,
    required this.languageHindi,
    required this.languageHinglish,
    required this.appUsage,
    required this.distinctAppCount,
    required this.dailyActivity,
  });

  static Future<InsightsSnapshot> default_() =>
      RustLib.instance.api.crateApiHistoryInsightsSnapshotDefault();

  @override
  int get hashCode =>
      totalWords.hashCode ^
      totalDictations.hashCode ^
      totalSpeechDurationMs.hashCode ^
      averageWordsPerMinute.hashCode ^
      currentStreakDays.hashCode ^
      longestStreakDays.hashCode ^
      wordsCorrected.hashCode ^
      dictionaryHits.hashCode ^
      languageEnglish.hashCode ^
      languageHindi.hashCode ^
      languageHinglish.hashCode ^
      appUsage.hashCode ^
      distinctAppCount.hashCode ^
      dailyActivity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsightsSnapshot &&
          runtimeType == other.runtimeType &&
          totalWords == other.totalWords &&
          totalDictations == other.totalDictations &&
          totalSpeechDurationMs == other.totalSpeechDurationMs &&
          averageWordsPerMinute == other.averageWordsPerMinute &&
          currentStreakDays == other.currentStreakDays &&
          longestStreakDays == other.longestStreakDays &&
          wordsCorrected == other.wordsCorrected &&
          dictionaryHits == other.dictionaryHits &&
          languageEnglish == other.languageEnglish &&
          languageHindi == other.languageHindi &&
          languageHinglish == other.languageHinglish &&
          appUsage == other.appUsage &&
          distinctAppCount == other.distinctAppCount &&
          dailyActivity == other.dailyActivity;
}

class StoredDictation {
  final String id;
  final PlatformInt64 createdAtMs;
  final String rawText;
  final String finalText;
  final String language;
  final String writingMode;
  final String sourceApplication;
  final int wordCount;
  final BigInt audioDurationMs;
  final BigInt speechDurationMs;
  final BigInt processingDurationMs;
  final String insertionStatus;

  const StoredDictation({
    required this.id,
    required this.createdAtMs,
    required this.rawText,
    required this.finalText,
    required this.language,
    required this.writingMode,
    required this.sourceApplication,
    required this.wordCount,
    required this.audioDurationMs,
    required this.speechDurationMs,
    required this.processingDurationMs,
    required this.insertionStatus,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      createdAtMs.hashCode ^
      rawText.hashCode ^
      finalText.hashCode ^
      language.hashCode ^
      writingMode.hashCode ^
      sourceApplication.hashCode ^
      wordCount.hashCode ^
      audioDurationMs.hashCode ^
      speechDurationMs.hashCode ^
      processingDurationMs.hashCode ^
      insertionStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredDictation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAtMs == other.createdAtMs &&
          rawText == other.rawText &&
          finalText == other.finalText &&
          language == other.language &&
          writingMode == other.writingMode &&
          sourceApplication == other.sourceApplication &&
          wordCount == other.wordCount &&
          audioDurationMs == other.audioDurationMs &&
          speechDurationMs == other.speechDurationMs &&
          processingDurationMs == other.processingDurationMs &&
          insertionStatus == other.insertionStatus;
}
