// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `asr_manifest`, `bundle_installed`, `directory_size`, `download_to_partial`, `download_verified`, `embedded_llm_model_path`, `ensure_parakeet_download`, `expected_minimum_bytes`, `file_present_with_min_size`, `install_bundle`, `models_dir`, `parakeet_installed`, `recommended_model_path`, `status_for`, `verified_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AsrBundle`, `AsrFile`, `AsrManifest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `embedded_llm_model_path_string`

/// Progress of the model download in flight, or `None` when nothing is running.
///
/// `#[frb(sync)]` because the overlay reads it once per frame while a download
/// is on; two relaxed atomic loads are far cheaper than a bridge round trip.
ModelDownloadProgress? modelDownloadProgress() =>
    RustLib.instance.api.crateApiModelsModelDownloadProgress();

/// Returns the supported multilingual starter model without accessing the network.
OfflineModelStatus recommendedModelStatus() =>
    RustLib.instance.api.crateApiModelsRecommendedModelStatus();

/// Downloads the official whisper.cpp multilingual base model to app support.
/// The partial file is verified before it atomically replaces any existing model.
Future<OfflineModelStatus> installRecommendedModel() =>
    RustLib.instance.api.crateApiModelsInstallRecommendedModel();

/// Downloads the embedded cleanup LLM (~2 GB) into the models directory,
/// verifying its SHA-256 before it atomically replaces any existing file.
Future<OfflineModelStatus> installEmbeddedLlmModel() =>
    RustLib.instance.api.crateApiModelsInstallEmbeddedLlmModel();

/// How far the current model download has got, or `None` when none is running.
class ModelDownloadProgress {
  final BigInt receivedBytes;
  final BigInt totalBytes;

  /// 0.0 to 1.0. Zero when the total is not yet known.
  final double fraction;

  const ModelDownloadProgress({
    required this.receivedBytes,
    required this.totalBytes,
    required this.fraction,
  });

  @override
  int get hashCode =>
      receivedBytes.hashCode ^ totalBytes.hashCode ^ fraction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelDownloadProgress &&
          runtimeType == other.runtimeType &&
          receivedBytes == other.receivedBytes &&
          totalBytes == other.totalBytes &&
          fraction == other.fraction;
}

class OfflineModelStatus {
  final String path;
  final bool installed;
  final BigInt sizeBytes;
  final String modelId;

  const OfflineModelStatus({
    required this.path,
    required this.installed,
    required this.sizeBytes,
    required this.modelId,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      installed.hashCode ^
      sizeBytes.hashCode ^
      modelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OfflineModelStatus &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          installed == other.installed &&
          sizeBytes == other.sizeBytes &&
          modelId == other.modelId;
}
