// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `download_to_partial`, `download_verified`, `expected_minimum_bytes`, `file_present_with_min_size`, `recommended_model_path`, `status_for`, `verified_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Returns the supported multilingual starter model without accessing the network.
OfflineModelStatus recommendedModelStatus() =>
    RustLib.instance.api.crateApiModelsRecommendedModelStatus();

/// Downloads the official whisper.cpp multilingual base model to app support.
/// The partial file is verified before it atomically replaces any existing model.
Future<OfflineModelStatus> installRecommendedModel() =>
    RustLib.instance.api.crateApiModelsInstallRecommendedModel();

class OfflineModelStatus {
  final String path;
  final bool installed;
  final BigInt sizeBytes;
  final String modelId;

  const OfflineModelStatus({
    required this.path,
    required this.installed,
    required this.sizeBytes,
    required this.modelId,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      installed.hashCode ^
      sizeBytes.hashCode ^
      modelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OfflineModelStatus &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          installed == other.installed &&
          sizeBytes == other.sizeBytes &&
          modelId == other.modelId;
}
