// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_entries`, `apply_vocabulary`, `build_hotword_prompt`, `hotword_prompt`, `validate_pair`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

Future<List<VocabularyEntry>> listVocabulary() =>
    RustLib.instance.api.crateApiPersonalizationListVocabulary();

Future<void> addVocabulary({required String spoken, required String written}) =>
    RustLib.instance.api.crateApiPersonalizationAddVocabulary(
      spoken: spoken,
      written: written,
    );

Future<void> deleteVocabulary({required String spoken}) => RustLib.instance.api
    .crateApiPersonalizationDeleteVocabulary(spoken: spoken);

/// Learns only when the user explicitly enabled the local edit flywheel.
Future<bool> recordUserEdit({
  required String original,
  required String corrected,
  required bool learningOptedIn,
}) => RustLib.instance.api.crateApiPersonalizationRecordUserEdit(
  original: original,
  corrected: corrected,
  learningOptedIn: learningOptedIn,
);

Future<VoiceStyleSnapshot> getVoiceStyleProfile() =>
    RustLib.instance.api.crateApiPersonalizationGetVoiceStyleProfile();

/// Writes opted-in correction triples to a user-owned JSONL file. This is an
/// explicit action and never uploads data.
Future<String> exportLearningExamples() =>
    RustLib.instance.api.crateApiPersonalizationExportLearningExamples();

class VocabularyEntry {
  final String spoken;
  final String written;
  final int useCount;

  const VocabularyEntry({
    required this.spoken,
    required this.written,
    required this.useCount,
  });

  @override
  int get hashCode => spoken.hashCode ^ written.hashCode ^ useCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VocabularyEntry &&
          runtimeType == other.runtimeType &&
          spoken == other.spoken &&
          written == other.written &&
          useCount == other.useCount;
}

class VoiceStyleSnapshot {
  final int sampleCount;
  final double averageSentenceWords;
  final double contractionRatio;
  final double lowercaseStartRatio;

  const VoiceStyleSnapshot({
    required this.sampleCount,
    required this.averageSentenceWords,
    required this.contractionRatio,
    required this.lowercaseStartRatio,
  });

  @override
  int get hashCode =>
      sampleCount.hashCode ^
      averageSentenceWords.hashCode ^
      contractionRatio.hashCode ^
      lowercaseStartRatio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceStyleSnapshot &&
          runtimeType == other.runtimeType &&
          sampleCount == other.sampleCount &&
          averageSentenceWords == other.averageSentenceWords &&
          contractionRatio == other.contractionRatio &&
          lowercaseStartRatio == other.lowercaseStartRatio;
}
