// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `settings_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

NativeSettings loadSettings() =>
    RustLib.instance.api.crateApiSettingsLoadSettings();

void saveSettings({required NativeSettings settings}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(settings: settings);

class NativeSettings {
  final String language;
  final String writingMode;
  final bool launchAtLogin;
  final bool showInDock;
  final bool keepModelsWarm;
  final bool showSwarBar;
  final bool dictationSounds;
  final bool muteMusic;
  final bool suggestions;
  final bool announcements;
  final bool milestones;
  final bool pasteAutomatically;
  final bool restoreClipboard;
  final bool learnFromEdits;
  final String modelPath;
  final String microphoneId;
  final String shortcutKey;
  final List<String> excludedApplications;
  final String enhancementProvider;
  final String providerEndpoint;
  final String providerModel;

  const NativeSettings({
    required this.language,
    required this.writingMode,
    required this.launchAtLogin,
    required this.showInDock,
    required this.keepModelsWarm,
    required this.showSwarBar,
    required this.dictationSounds,
    required this.muteMusic,
    required this.suggestions,
    required this.announcements,
    required this.milestones,
    required this.pasteAutomatically,
    required this.restoreClipboard,
    required this.learnFromEdits,
    required this.modelPath,
    required this.microphoneId,
    required this.shortcutKey,
    required this.excludedApplications,
    required this.enhancementProvider,
    required this.providerEndpoint,
    required this.providerModel,
  });

  static Future<NativeSettings> default_() =>
      RustLib.instance.api.crateApiSettingsNativeSettingsDefault();

  @override
  int get hashCode =>
      language.hashCode ^
      writingMode.hashCode ^
      launchAtLogin.hashCode ^
      showInDock.hashCode ^
      keepModelsWarm.hashCode ^
      showSwarBar.hashCode ^
      dictationSounds.hashCode ^
      muteMusic.hashCode ^
      suggestions.hashCode ^
      announcements.hashCode ^
      milestones.hashCode ^
      pasteAutomatically.hashCode ^
      restoreClipboard.hashCode ^
      learnFromEdits.hashCode ^
      modelPath.hashCode ^
      microphoneId.hashCode ^
      shortcutKey.hashCode ^
      excludedApplications.hashCode ^
      enhancementProvider.hashCode ^
      providerEndpoint.hashCode ^
      providerModel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSettings &&
          runtimeType == other.runtimeType &&
          language == other.language &&
          writingMode == other.writingMode &&
          launchAtLogin == other.launchAtLogin &&
          showInDock == other.showInDock &&
          keepModelsWarm == other.keepModelsWarm &&
          showSwarBar == other.showSwarBar &&
          dictationSounds == other.dictationSounds &&
          muteMusic == other.muteMusic &&
          suggestions == other.suggestions &&
          announcements == other.announcements &&
          milestones == other.milestones &&
          pasteAutomatically == other.pasteAutomatically &&
          restoreClipboard == other.restoreClipboard &&
          learnFromEdits == other.learnFromEdits &&
          modelPath == other.modelPath &&
          microphoneId == other.microphoneId &&
          shortcutKey == other.shortcutKey &&
          excludedApplications == other.excludedApplications &&
          enhancementProvider == other.enhancementProvider &&
          providerEndpoint == other.providerEndpoint &&
          providerModel == other.providerModel;
}
