// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `configured_history_retention_days`, `normalize_retention_days`, `settings_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

NativeSettings loadSettings() =>
    RustLib.instance.api.crateApiSettingsLoadSettings();

void saveSettings({required NativeSettings settings}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(settings: settings);

/// What Swar persists between launches.
///
/// Every field here must be read by something that changes behaviour. Eight
/// were removed once nothing read them: `language`, `launch_at_login`,
/// `show_in_dock`, `dictation_sounds`, `mute_music`, `suggestions`,
/// `announcements`, and `milestones`. They survived the removal of their
/// Settings rows and went on being written to disk, which left a settings file
/// stating things about the product that were not true. `launch_at_login` in
/// particular persisted as `true` on machines where no launch agent has ever
/// existed.
///
/// `#[serde(default)]` plus serde's habit of ignoring unknown keys means an
/// existing settings.json holding those keys still loads; they are simply
/// dropped the next time it is written. No migration is needed.
///
/// When one of those features is built, its field comes back in the same
/// commit as its implementation, so it is true from the first line.
class NativeSettings {
  final String writingMode;
  final bool keepModelsWarm;
  final bool showSwarBar;
  final bool pasteAutomatically;
  final bool restoreClipboard;
  final bool learnFromEdits;
  final String modelPath;
  final String microphoneId;
  final String shortcutKey;
  final List<String> excludedApplications;
  final String enhancementProvider;
  final String providerEndpoint;
  final String providerModel;

  /// How many days of local dictation history to keep before it is pruned.
  /// One of 30/90/180/365; other values fall back to the default.
  final int historyRetentionDays;

  const NativeSettings({
    required this.writingMode,
    required this.keepModelsWarm,
    required this.showSwarBar,
    required this.pasteAutomatically,
    required this.restoreClipboard,
    required this.learnFromEdits,
    required this.modelPath,
    required this.microphoneId,
    required this.shortcutKey,
    required this.excludedApplications,
    required this.enhancementProvider,
    required this.providerEndpoint,
    required this.providerModel,
    required this.historyRetentionDays,
  });

  static Future<NativeSettings> default_() =>
      RustLib.instance.api.crateApiSettingsNativeSettingsDefault();

  @override
  int get hashCode =>
      writingMode.hashCode ^
      keepModelsWarm.hashCode ^
      showSwarBar.hashCode ^
      pasteAutomatically.hashCode ^
      restoreClipboard.hashCode ^
      learnFromEdits.hashCode ^
      modelPath.hashCode ^
      microphoneId.hashCode ^
      shortcutKey.hashCode ^
      excludedApplications.hashCode ^
      enhancementProvider.hashCode ^
      providerEndpoint.hashCode ^
      providerModel.hashCode ^
      historyRetentionDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSettings &&
          runtimeType == other.runtimeType &&
          writingMode == other.writingMode &&
          keepModelsWarm == other.keepModelsWarm &&
          showSwarBar == other.showSwarBar &&
          pasteAutomatically == other.pasteAutomatically &&
          restoreClipboard == other.restoreClipboard &&
          learnFromEdits == other.learnFromEdits &&
          modelPath == other.modelPath &&
          microphoneId == other.microphoneId &&
          shortcutKey == other.shortcutKey &&
          excludedApplications == other.excludedApplications &&
          enhancementProvider == other.enhancementProvider &&
          providerEndpoint == other.providerEndpoint &&
          providerModel == other.providerModel &&
          historyRetentionDays == other.historyRetentionDays;
}
