// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/diagnostics.dart';
import 'api/dictation.dart';
import 'api/history.dart';
import 'api/models.dart';
import 'api/personalization.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -89260601;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'swar_core',
        ioDirectory: '../../crates/swar_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiPersonalizationAddVocabulary({
    required String spoken,
    required String written,
  });

  Future<AppUsage> crateApiHistoryAppUsageDefault();

  Future<void> crateApiDictationCancelDictationSession({
    required String sessionId,
  });

  Future<void> crateApiHistoryClearLocalHistory();

  Future<bool> crateApiHistoryCorrectDictation({
    required String id,
    required String correctedText,
    required bool learningOptedIn,
  });

  Future<void> crateApiPersonalizationDeleteVocabulary({
    required String spoken,
  });

  Future<String> crateApiPersonalizationExportLearningExamples();

  Future<DictationCompletion> crateApiDictationFinishDictationSession({
    required String sessionId,
  });

  String crateApiDiagnosticsGetCoreVersion();

  Future<VoiceStyleSnapshot> crateApiPersonalizationGetVoiceStyleProfile();

  OfflineModelStatus crateApiModelsIndicPackStatus();

  Future<String> crateApiHistoryInitializeLocalStore();

  Future<InsightsSnapshot> crateApiHistoryInsightsSnapshotDefault();

  Future<OfflineModelStatus> crateApiModelsInstallEmbeddedLlmModel();

  Future<OfflineModelStatus> crateApiModelsInstallIndicModels();

  Future<OfflineModelStatus> crateApiModelsInstallRecommendedModel();

  Future<List<MicrophoneDevice>> crateApiDictationListMicrophones();

  Future<List<VocabularyEntry>> crateApiPersonalizationListVocabulary();

  Future<HistoryPage> crateApiHistoryLoadHistoryPage({
    required String searchText,
    required int offset,
    required int limit,
  });

  Future<InsightsSnapshot> crateApiHistoryLoadInsightsSnapshot();

  NativeSettings crateApiSettingsLoadSettings();

  Future<NativeSettings> crateApiSettingsNativeSettingsDefault();

  bool crateApiDictationOfflineModelIsReady({required String modelPath});

  Future<int> crateApiDictationPrepareAudioCapture({
    required String microphoneId,
  });

  Future<bool> crateApiDictationPrepareDictationEngine({
    required String modelPath,
  });

  OfflineModelStatus crateApiModelsRecommendedModelStatus();

  Future<bool> crateApiPersonalizationRecordUserEdit({
    required String original,
    required String corrected,
    required bool learningOptedIn,
  });

  Future<void> crateApiDictationReleaseDictationEngine();

  void crateApiSettingsSaveSettings({required NativeSettings settings});

  Stream<DictationEvent> crateApiDictationStartDictationSession({
    required DictationSessionConfig config,
  });

  Stream<int> crateApiDiagnosticsStreamDemoEvents();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiPersonalizationAddVocabulary({
    required String spoken,
    required String written,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(spoken, serializer);
          sse_encode_String(written, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPersonalizationAddVocabularyConstMeta,
        argValues: [spoken, written],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPersonalizationAddVocabularyConstMeta =>
      const TaskConstMeta(
        debugName: "add_vocabulary",
        argNames: ["spoken", "written"],
      );

  @override
  Future<AppUsage> crateApiHistoryAppUsageDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_usage,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHistoryAppUsageDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryAppUsageDefaultConstMeta =>
      const TaskConstMeta(debugName: "app_usage_default", argNames: []);

  @override
  Future<void> crateApiDictationCancelDictationSession({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDictationCancelDictationSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDictationCancelDictationSessionConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_dictation_session",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiHistoryClearLocalHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHistoryClearLocalHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryClearLocalHistoryConstMeta =>
      const TaskConstMeta(debugName: "clear_local_history", argNames: []);

  @override
  Future<bool> crateApiHistoryCorrectDictation({
    required String id,
    required String correctedText,
    required bool learningOptedIn,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(correctedText, serializer);
          sse_encode_bool(learningOptedIn, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHistoryCorrectDictationConstMeta,
        argValues: [id, correctedText, learningOptedIn],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryCorrectDictationConstMeta =>
      const TaskConstMeta(
        debugName: "correct_dictation",
        argNames: ["id", "correctedText", "learningOptedIn"],
      );

  @override
  Future<void> crateApiPersonalizationDeleteVocabulary({
    required String spoken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(spoken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPersonalizationDeleteVocabularyConstMeta,
        argValues: [spoken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPersonalizationDeleteVocabularyConstMeta =>
      const TaskConstMeta(debugName: "delete_vocabulary", argNames: ["spoken"]);

  @override
  Future<String> crateApiPersonalizationExportLearningExamples() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPersonalizationExportLearningExamplesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPersonalizationExportLearningExamplesConstMeta =>
      const TaskConstMeta(debugName: "export_learning_examples", argNames: []);

  @override
  Future<DictationCompletion> crateApiDictationFinishDictationSession({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dictation_completion,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDictationFinishDictationSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDictationFinishDictationSessionConstMeta =>
      const TaskConstMeta(
        debugName: "finish_dictation_session",
        argNames: ["sessionId"],
      );

  @override
  String crateApiDiagnosticsGetCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiagnosticsGetCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagnosticsGetCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "get_core_version", argNames: []);

  @override
  Future<VoiceStyleSnapshot> crateApiPersonalizationGetVoiceStyleProfile() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_voice_style_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPersonalizationGetVoiceStyleProfileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPersonalizationGetVoiceStyleProfileConstMeta =>
      const TaskConstMeta(debugName: "get_voice_style_profile", argNames: []);

  @override
  OfflineModelStatus crateApiModelsIndicPackStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_offline_model_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsIndicPackStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsIndicPackStatusConstMeta =>
      const TaskConstMeta(debugName: "indic_pack_status", argNames: []);

  @override
  Future<String> crateApiHistoryInitializeLocalStore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHistoryInitializeLocalStoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryInitializeLocalStoreConstMeta =>
      const TaskConstMeta(debugName: "initialize_local_store", argNames: []);

  @override
  Future<InsightsSnapshot> crateApiHistoryInsightsSnapshotDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_insights_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHistoryInsightsSnapshotDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryInsightsSnapshotDefaultConstMeta =>
      const TaskConstMeta(debugName: "insights_snapshot_default", argNames: []);

  @override
  Future<OfflineModelStatus> crateApiModelsInstallEmbeddedLlmModel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_offline_model_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModelsInstallEmbeddedLlmModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsInstallEmbeddedLlmModelConstMeta =>
      const TaskConstMeta(
        debugName: "install_embedded_llm_model",
        argNames: [],
      );

  @override
  Future<OfflineModelStatus> crateApiModelsInstallIndicModels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_offline_model_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModelsInstallIndicModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsInstallIndicModelsConstMeta =>
      const TaskConstMeta(debugName: "install_indic_models", argNames: []);

  @override
  Future<OfflineModelStatus> crateApiModelsInstallRecommendedModel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_offline_model_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModelsInstallRecommendedModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsInstallRecommendedModelConstMeta =>
      const TaskConstMeta(debugName: "install_recommended_model", argNames: []);

  @override
  Future<List<MicrophoneDevice>> crateApiDictationListMicrophones() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_microphone_device,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDictationListMicrophonesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDictationListMicrophonesConstMeta =>
      const TaskConstMeta(debugName: "list_microphones", argNames: []);

  @override
  Future<List<VocabularyEntry>> crateApiPersonalizationListVocabulary() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_vocabulary_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPersonalizationListVocabularyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPersonalizationListVocabularyConstMeta =>
      const TaskConstMeta(debugName: "list_vocabulary", argNames: []);

  @override
  Future<HistoryPage> crateApiHistoryLoadHistoryPage({
    required String searchText,
    required int offset,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(searchText, serializer);
          sse_encode_u_32(offset, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_history_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHistoryLoadHistoryPageConstMeta,
        argValues: [searchText, offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryLoadHistoryPageConstMeta =>
      const TaskConstMeta(
        debugName: "load_history_page",
        argNames: ["searchText", "offset", "limit"],
      );

  @override
  Future<InsightsSnapshot> crateApiHistoryLoadInsightsSnapshot() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_insights_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHistoryLoadInsightsSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryLoadInsightsSnapshotConstMeta =>
      const TaskConstMeta(debugName: "load_insights_snapshot", argNames: []);

  @override
  NativeSettings crateApiSettingsLoadSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_settings,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsLoadSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsLoadSettingsConstMeta =>
      const TaskConstMeta(debugName: "load_settings", argNames: []);

  @override
  Future<NativeSettings> crateApiSettingsNativeSettingsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsNativeSettingsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsNativeSettingsDefaultConstMeta =>
      const TaskConstMeta(debugName: "native_settings_default", argNames: []);

  @override
  bool crateApiDictationOfflineModelIsReady({required String modelPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDictationOfflineModelIsReadyConstMeta,
        argValues: [modelPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDictationOfflineModelIsReadyConstMeta =>
      const TaskConstMeta(
        debugName: "offline_model_is_ready",
        argNames: ["modelPath"],
      );

  @override
  Future<int> crateApiDictationPrepareAudioCapture({
    required String microphoneId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(microphoneId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDictationPrepareAudioCaptureConstMeta,
        argValues: [microphoneId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDictationPrepareAudioCaptureConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_audio_capture",
        argNames: ["microphoneId"],
      );

  @override
  Future<bool> crateApiDictationPrepareDictationEngine({
    required String modelPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDictationPrepareDictationEngineConstMeta,
        argValues: [modelPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDictationPrepareDictationEngineConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_dictation_engine",
        argNames: ["modelPath"],
      );

  @override
  OfflineModelStatus crateApiModelsRecommendedModelStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_offline_model_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModelsRecommendedModelStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsRecommendedModelStatusConstMeta =>
      const TaskConstMeta(debugName: "recommended_model_status", argNames: []);

  @override
  Future<bool> crateApiPersonalizationRecordUserEdit({
    required String original,
    required String corrected,
    required bool learningOptedIn,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(original, serializer);
          sse_encode_String(corrected, serializer);
          sse_encode_bool(learningOptedIn, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPersonalizationRecordUserEditConstMeta,
        argValues: [original, corrected, learningOptedIn],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPersonalizationRecordUserEditConstMeta =>
      const TaskConstMeta(
        debugName: "record_user_edit",
        argNames: ["original", "corrected", "learningOptedIn"],
      );

  @override
  Future<void> crateApiDictationReleaseDictationEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDictationReleaseDictationEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDictationReleaseDictationEngineConstMeta =>
      const TaskConstMeta(debugName: "release_dictation_engine", argNames: []);

  @override
  void crateApiSettingsSaveSettings({required NativeSettings settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_native_settings(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsSaveSettingsConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSaveSettingsConstMeta =>
      const TaskConstMeta(debugName: "save_settings", argNames: ["settings"]);

  @override
  Stream<DictationEvent> crateApiDictationStartDictationSession({
    required DictationSessionConfig config,
  }) {
    final sink = RustStreamSink<DictationEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_dictation_session_config(config, serializer);
            sse_encode_StreamSink_dictation_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 30,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_String,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiDictationStartDictationSessionConstMeta,
          argValues: [config, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDictationStartDictationSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_dictation_session",
        argNames: ["config", "sink"],
      );

  @override
  Stream<int> crateApiDiagnosticsStreamDemoEvents() {
    final sink = RustStreamSink<int>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_u_32_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 31,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiDiagnosticsStreamDemoEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDiagnosticsStreamDemoEventsConstMeta =>
      const TaskConstMeta(debugName: "stream_demo_events", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DictationEvent> dco_decode_StreamSink_dictation_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_u_32_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppUsage dco_decode_app_usage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AppUsage(
      name: dco_decode_String(arr[0]),
      count: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DictationSessionConfig dco_decode_box_autoadd_dictation_session_config(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dictation_session_config(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  NativeSettings dco_decode_box_autoadd_native_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_settings(raw);
  }

  @protected
  DictationCompletion dco_decode_dictation_completion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DictationCompletion(
      sessionId: dco_decode_String(arr[0]),
      rawText: dco_decode_String(arr[1]),
      finalText: dco_decode_String(arr[2]),
      audioDurationMs: dco_decode_u_64(arr[3]),
      processingDurationMs: dco_decode_u_64(arr[4]),
      insertionStatus: dco_decode_String(arr[5]),
      insertionMethod: dco_decode_String(arr[6]),
    );
  }

  @protected
  DictationEvent dco_decode_dictation_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DictationEvent(
      sessionId: dco_decode_String(arr[0]),
      kind: dco_decode_dictation_event_kind(arr[1]),
      audioLevel: dco_decode_opt_box_autoadd_f_64(arr[2]),
      message: dco_decode_opt_String(arr[3]),
      timestampMs: dco_decode_u_64(arr[4]),
      previousState: dco_decode_dictation_lifecycle_state(arr[5]),
      currentState: dco_decode_dictation_lifecycle_state(arr[6]),
      reason: dco_decode_String(arr[7]),
      partialText: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  DictationEventKind dco_decode_dictation_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DictationEventKind.values[raw as int];
  }

  @protected
  DictationLifecycleState dco_decode_dictation_lifecycle_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DictationLifecycleState.values[raw as int];
  }

  @protected
  DictationSessionConfig dco_decode_dictation_session_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return DictationSessionConfig(
      modelPath: dco_decode_String(arr[0]),
      microphoneId: dco_decode_String(arr[1]),
      language: dco_decode_String(arr[2]),
      writingMode: dco_decode_String(arr[3]),
      sourceApplication: dco_decode_String(arr[4]),
      pasteAutomatically: dco_decode_bool(arr[5]),
      restoreClipboard: dco_decode_bool(arr[6]),
      maximumSeconds: dco_decode_u_32(arr[7]),
      enableLivePreview: dco_decode_bool(arr[8]),
      enhancementProvider: dco_decode_String(arr[9]),
      providerEndpoint: dco_decode_String(arr[10]),
      providerModel: dco_decode_String(arr[11]),
      providerApiKey: dco_decode_String(arr[12]),
      isSensitive: dco_decode_bool(arr[13]),
      cursorTextBefore: dco_decode_String(arr[14]),
      cursorTextAfter: dco_decode_String(arr[15]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HistoryPage dco_decode_history_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HistoryPage(
      totalCount: dco_decode_u_32(arr[0]),
      records: dco_decode_list_stored_dictation(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  InsightsSnapshot dco_decode_insights_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return InsightsSnapshot(
      totalWords: dco_decode_u_64(arr[0]),
      totalDictations: dco_decode_u_64(arr[1]),
      totalSpeechDurationMs: dco_decode_u_64(arr[2]),
      averageWordsPerMinute: dco_decode_f_64(arr[3]),
      currentStreakDays: dco_decode_u_32(arr[4]),
      longestStreakDays: dco_decode_u_32(arr[5]),
      wordsCorrected: dco_decode_u_64(arr[6]),
      dictionaryHits: dco_decode_u_64(arr[7]),
      languageEnglish: dco_decode_u_64(arr[8]),
      languageHindi: dco_decode_u_64(arr[9]),
      languageHinglish: dco_decode_u_64(arr[10]),
      appUsage: dco_decode_list_app_usage(arr[11]),
      distinctAppCount: dco_decode_u_64(arr[12]),
      dailyActivity: dco_decode_list_prim_u_32_strict(arr[13]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AppUsage> dco_decode_list_app_usage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_app_usage).toList();
  }

  @protected
  List<MicrophoneDevice> dco_decode_list_microphone_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_microphone_device).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StoredDictation> dco_decode_list_stored_dictation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stored_dictation).toList();
  }

  @protected
  List<VocabularyEntry> dco_decode_list_vocabulary_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vocabulary_entry).toList();
  }

  @protected
  MicrophoneDevice dco_decode_microphone_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MicrophoneDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      isDefault: dco_decode_bool(arr[2]),
      isBuiltIn: dco_decode_bool(arr[3]),
    );
  }

  @protected
  NativeSettings dco_decode_native_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 22)
      throw Exception('unexpected arr length: expect 22 but see ${arr.length}');
    return NativeSettings(
      language: dco_decode_String(arr[0]),
      writingMode: dco_decode_String(arr[1]),
      launchAtLogin: dco_decode_bool(arr[2]),
      showInDock: dco_decode_bool(arr[3]),
      keepModelsWarm: dco_decode_bool(arr[4]),
      showSwarBar: dco_decode_bool(arr[5]),
      dictationSounds: dco_decode_bool(arr[6]),
      muteMusic: dco_decode_bool(arr[7]),
      suggestions: dco_decode_bool(arr[8]),
      announcements: dco_decode_bool(arr[9]),
      milestones: dco_decode_bool(arr[10]),
      pasteAutomatically: dco_decode_bool(arr[11]),
      restoreClipboard: dco_decode_bool(arr[12]),
      learnFromEdits: dco_decode_bool(arr[13]),
      modelPath: dco_decode_String(arr[14]),
      microphoneId: dco_decode_String(arr[15]),
      shortcutKey: dco_decode_String(arr[16]),
      excludedApplications: dco_decode_list_String(arr[17]),
      enhancementProvider: dco_decode_String(arr[18]),
      providerEndpoint: dco_decode_String(arr[19]),
      providerModel: dco_decode_String(arr[20]),
      historyRetentionDays: dco_decode_u_32(arr[21]),
    );
  }

  @protected
  OfflineModelStatus dco_decode_offline_model_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OfflineModelStatus(
      path: dco_decode_String(arr[0]),
      installed: dco_decode_bool(arr[1]),
      sizeBytes: dco_decode_u_64(arr[2]),
      modelId: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  StoredDictation dco_decode_stored_dictation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return StoredDictation(
      id: dco_decode_String(arr[0]),
      createdAtMs: dco_decode_i_64(arr[1]),
      rawText: dco_decode_String(arr[2]),
      finalText: dco_decode_String(arr[3]),
      language: dco_decode_String(arr[4]),
      writingMode: dco_decode_String(arr[5]),
      sourceApplication: dco_decode_String(arr[6]),
      wordCount: dco_decode_u_32(arr[7]),
      audioDurationMs: dco_decode_u_64(arr[8]),
      speechDurationMs: dco_decode_u_64(arr[9]),
      processingDurationMs: dco_decode_u_64(arr[10]),
      insertionStatus: dco_decode_String(arr[11]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VocabularyEntry dco_decode_vocabulary_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VocabularyEntry(
      spoken: dco_decode_String(arr[0]),
      written: dco_decode_String(arr[1]),
      useCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  VoiceStyleSnapshot dco_decode_voice_style_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VoiceStyleSnapshot(
      sampleCount: dco_decode_u_32(arr[0]),
      averageSentenceWords: dco_decode_f_64(arr[1]),
      contractionRatio: dco_decode_f_64(arr[2]),
      lowercaseStartRatio: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DictationEvent> sse_decode_StreamSink_dictation_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_u_32_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppUsage sse_decode_app_usage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_count = sse_decode_u_64(deserializer);
    return AppUsage(name: var_name, count: var_count);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DictationSessionConfig sse_decode_box_autoadd_dictation_session_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dictation_session_config(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  NativeSettings sse_decode_box_autoadd_native_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_settings(deserializer));
  }

  @protected
  DictationCompletion sse_decode_dictation_completion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_rawText = sse_decode_String(deserializer);
    var var_finalText = sse_decode_String(deserializer);
    var var_audioDurationMs = sse_decode_u_64(deserializer);
    var var_processingDurationMs = sse_decode_u_64(deserializer);
    var var_insertionStatus = sse_decode_String(deserializer);
    var var_insertionMethod = sse_decode_String(deserializer);
    return DictationCompletion(
      sessionId: var_sessionId,
      rawText: var_rawText,
      finalText: var_finalText,
      audioDurationMs: var_audioDurationMs,
      processingDurationMs: var_processingDurationMs,
      insertionStatus: var_insertionStatus,
      insertionMethod: var_insertionMethod,
    );
  }

  @protected
  DictationEvent sse_decode_dictation_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_kind = sse_decode_dictation_event_kind(deserializer);
    var var_audioLevel = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_previousState = sse_decode_dictation_lifecycle_state(deserializer);
    var var_currentState = sse_decode_dictation_lifecycle_state(deserializer);
    var var_reason = sse_decode_String(deserializer);
    var var_partialText = sse_decode_opt_String(deserializer);
    return DictationEvent(
      sessionId: var_sessionId,
      kind: var_kind,
      audioLevel: var_audioLevel,
      message: var_message,
      timestampMs: var_timestampMs,
      previousState: var_previousState,
      currentState: var_currentState,
      reason: var_reason,
      partialText: var_partialText,
    );
  }

  @protected
  DictationEventKind sse_decode_dictation_event_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DictationEventKind.values[inner];
  }

  @protected
  DictationLifecycleState sse_decode_dictation_lifecycle_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DictationLifecycleState.values[inner];
  }

  @protected
  DictationSessionConfig sse_decode_dictation_session_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelPath = sse_decode_String(deserializer);
    var var_microphoneId = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_writingMode = sse_decode_String(deserializer);
    var var_sourceApplication = sse_decode_String(deserializer);
    var var_pasteAutomatically = sse_decode_bool(deserializer);
    var var_restoreClipboard = sse_decode_bool(deserializer);
    var var_maximumSeconds = sse_decode_u_32(deserializer);
    var var_enableLivePreview = sse_decode_bool(deserializer);
    var var_enhancementProvider = sse_decode_String(deserializer);
    var var_providerEndpoint = sse_decode_String(deserializer);
    var var_providerModel = sse_decode_String(deserializer);
    var var_providerApiKey = sse_decode_String(deserializer);
    var var_isSensitive = sse_decode_bool(deserializer);
    var var_cursorTextBefore = sse_decode_String(deserializer);
    var var_cursorTextAfter = sse_decode_String(deserializer);
    return DictationSessionConfig(
      modelPath: var_modelPath,
      microphoneId: var_microphoneId,
      language: var_language,
      writingMode: var_writingMode,
      sourceApplication: var_sourceApplication,
      pasteAutomatically: var_pasteAutomatically,
      restoreClipboard: var_restoreClipboard,
      maximumSeconds: var_maximumSeconds,
      enableLivePreview: var_enableLivePreview,
      enhancementProvider: var_enhancementProvider,
      providerEndpoint: var_providerEndpoint,
      providerModel: var_providerModel,
      providerApiKey: var_providerApiKey,
      isSensitive: var_isSensitive,
      cursorTextBefore: var_cursorTextBefore,
      cursorTextAfter: var_cursorTextAfter,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HistoryPage sse_decode_history_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalCount = sse_decode_u_32(deserializer);
    var var_records = sse_decode_list_stored_dictation(deserializer);
    return HistoryPage(totalCount: var_totalCount, records: var_records);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  InsightsSnapshot sse_decode_insights_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalWords = sse_decode_u_64(deserializer);
    var var_totalDictations = sse_decode_u_64(deserializer);
    var var_totalSpeechDurationMs = sse_decode_u_64(deserializer);
    var var_averageWordsPerMinute = sse_decode_f_64(deserializer);
    var var_currentStreakDays = sse_decode_u_32(deserializer);
    var var_longestStreakDays = sse_decode_u_32(deserializer);
    var var_wordsCorrected = sse_decode_u_64(deserializer);
    var var_dictionaryHits = sse_decode_u_64(deserializer);
    var var_languageEnglish = sse_decode_u_64(deserializer);
    var var_languageHindi = sse_decode_u_64(deserializer);
    var var_languageHinglish = sse_decode_u_64(deserializer);
    var var_appUsage = sse_decode_list_app_usage(deserializer);
    var var_distinctAppCount = sse_decode_u_64(deserializer);
    var var_dailyActivity = sse_decode_list_prim_u_32_strict(deserializer);
    return InsightsSnapshot(
      totalWords: var_totalWords,
      totalDictations: var_totalDictations,
      totalSpeechDurationMs: var_totalSpeechDurationMs,
      averageWordsPerMinute: var_averageWordsPerMinute,
      currentStreakDays: var_currentStreakDays,
      longestStreakDays: var_longestStreakDays,
      wordsCorrected: var_wordsCorrected,
      dictionaryHits: var_dictionaryHits,
      languageEnglish: var_languageEnglish,
      languageHindi: var_languageHindi,
      languageHinglish: var_languageHinglish,
      appUsage: var_appUsage,
      distinctAppCount: var_distinctAppCount,
      dailyActivity: var_dailyActivity,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AppUsage> sse_decode_list_app_usage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AppUsage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_app_usage(deserializer));
    }
    return ans_;
  }

  @protected
  List<MicrophoneDevice> sse_decode_list_microphone_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MicrophoneDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_microphone_device(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StoredDictation> sse_decode_list_stored_dictation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoredDictation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stored_dictation(deserializer));
    }
    return ans_;
  }

  @protected
  List<VocabularyEntry> sse_decode_list_vocabulary_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VocabularyEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vocabulary_entry(deserializer));
    }
    return ans_;
  }

  @protected
  MicrophoneDevice sse_decode_microphone_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isDefault = sse_decode_bool(deserializer);
    var var_isBuiltIn = sse_decode_bool(deserializer);
    return MicrophoneDevice(
      id: var_id,
      name: var_name,
      isDefault: var_isDefault,
      isBuiltIn: var_isBuiltIn,
    );
  }

  @protected
  NativeSettings sse_decode_native_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_language = sse_decode_String(deserializer);
    var var_writingMode = sse_decode_String(deserializer);
    var var_launchAtLogin = sse_decode_bool(deserializer);
    var var_showInDock = sse_decode_bool(deserializer);
    var var_keepModelsWarm = sse_decode_bool(deserializer);
    var var_showSwarBar = sse_decode_bool(deserializer);
    var var_dictationSounds = sse_decode_bool(deserializer);
    var var_muteMusic = sse_decode_bool(deserializer);
    var var_suggestions = sse_decode_bool(deserializer);
    var var_announcements = sse_decode_bool(deserializer);
    var var_milestones = sse_decode_bool(deserializer);
    var var_pasteAutomatically = sse_decode_bool(deserializer);
    var var_restoreClipboard = sse_decode_bool(deserializer);
    var var_learnFromEdits = sse_decode_bool(deserializer);
    var var_modelPath = sse_decode_String(deserializer);
    var var_microphoneId = sse_decode_String(deserializer);
    var var_shortcutKey = sse_decode_String(deserializer);
    var var_excludedApplications = sse_decode_list_String(deserializer);
    var var_enhancementProvider = sse_decode_String(deserializer);
    var var_providerEndpoint = sse_decode_String(deserializer);
    var var_providerModel = sse_decode_String(deserializer);
    var var_historyRetentionDays = sse_decode_u_32(deserializer);
    return NativeSettings(
      language: var_language,
      writingMode: var_writingMode,
      launchAtLogin: var_launchAtLogin,
      showInDock: var_showInDock,
      keepModelsWarm: var_keepModelsWarm,
      showSwarBar: var_showSwarBar,
      dictationSounds: var_dictationSounds,
      muteMusic: var_muteMusic,
      suggestions: var_suggestions,
      announcements: var_announcements,
      milestones: var_milestones,
      pasteAutomatically: var_pasteAutomatically,
      restoreClipboard: var_restoreClipboard,
      learnFromEdits: var_learnFromEdits,
      modelPath: var_modelPath,
      microphoneId: var_microphoneId,
      shortcutKey: var_shortcutKey,
      excludedApplications: var_excludedApplications,
      enhancementProvider: var_enhancementProvider,
      providerEndpoint: var_providerEndpoint,
      providerModel: var_providerModel,
      historyRetentionDays: var_historyRetentionDays,
    );
  }

  @protected
  OfflineModelStatus sse_decode_offline_model_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_installed = sse_decode_bool(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_modelId = sse_decode_String(deserializer);
    return OfflineModelStatus(
      path: var_path,
      installed: var_installed,
      sizeBytes: var_sizeBytes,
      modelId: var_modelId,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StoredDictation sse_decode_stored_dictation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    var var_rawText = sse_decode_String(deserializer);
    var var_finalText = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_writingMode = sse_decode_String(deserializer);
    var var_sourceApplication = sse_decode_String(deserializer);
    var var_wordCount = sse_decode_u_32(deserializer);
    var var_audioDurationMs = sse_decode_u_64(deserializer);
    var var_speechDurationMs = sse_decode_u_64(deserializer);
    var var_processingDurationMs = sse_decode_u_64(deserializer);
    var var_insertionStatus = sse_decode_String(deserializer);
    return StoredDictation(
      id: var_id,
      createdAtMs: var_createdAtMs,
      rawText: var_rawText,
      finalText: var_finalText,
      language: var_language,
      writingMode: var_writingMode,
      sourceApplication: var_sourceApplication,
      wordCount: var_wordCount,
      audioDurationMs: var_audioDurationMs,
      speechDurationMs: var_speechDurationMs,
      processingDurationMs: var_processingDurationMs,
      insertionStatus: var_insertionStatus,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VocabularyEntry sse_decode_vocabulary_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spoken = sse_decode_String(deserializer);
    var var_written = sse_decode_String(deserializer);
    var var_useCount = sse_decode_u_32(deserializer);
    return VocabularyEntry(
      spoken: var_spoken,
      written: var_written,
      useCount: var_useCount,
    );
  }

  @protected
  VoiceStyleSnapshot sse_decode_voice_style_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sampleCount = sse_decode_u_32(deserializer);
    var var_averageSentenceWords = sse_decode_f_64(deserializer);
    var var_contractionRatio = sse_decode_f_64(deserializer);
    var var_lowercaseStartRatio = sse_decode_f_64(deserializer);
    return VoiceStyleSnapshot(
      sampleCount: var_sampleCount,
      averageSentenceWords: var_averageSentenceWords,
      contractionRatio: var_contractionRatio,
      lowercaseStartRatio: var_lowercaseStartRatio,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_dictation_event_Sse(
    RustStreamSink<DictationEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_dictation_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_u_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_usage(AppUsage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.count, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dictation_session_config(
    DictationSessionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dictation_session_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_settings(
    NativeSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_settings(self, serializer);
  }

  @protected
  void sse_encode_dictation_completion(
    DictationCompletion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.rawText, serializer);
    sse_encode_String(self.finalText, serializer);
    sse_encode_u_64(self.audioDurationMs, serializer);
    sse_encode_u_64(self.processingDurationMs, serializer);
    sse_encode_String(self.insertionStatus, serializer);
    sse_encode_String(self.insertionMethod, serializer);
  }

  @protected
  void sse_encode_dictation_event(
    DictationEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_dictation_event_kind(self.kind, serializer);
    sse_encode_opt_box_autoadd_f_64(self.audioLevel, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_dictation_lifecycle_state(self.previousState, serializer);
    sse_encode_dictation_lifecycle_state(self.currentState, serializer);
    sse_encode_String(self.reason, serializer);
    sse_encode_opt_String(self.partialText, serializer);
  }

  @protected
  void sse_encode_dictation_event_kind(
    DictationEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dictation_lifecycle_state(
    DictationLifecycleState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dictation_session_config(
    DictationSessionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelPath, serializer);
    sse_encode_String(self.microphoneId, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.writingMode, serializer);
    sse_encode_String(self.sourceApplication, serializer);
    sse_encode_bool(self.pasteAutomatically, serializer);
    sse_encode_bool(self.restoreClipboard, serializer);
    sse_encode_u_32(self.maximumSeconds, serializer);
    sse_encode_bool(self.enableLivePreview, serializer);
    sse_encode_String(self.enhancementProvider, serializer);
    sse_encode_String(self.providerEndpoint, serializer);
    sse_encode_String(self.providerModel, serializer);
    sse_encode_String(self.providerApiKey, serializer);
    sse_encode_bool(self.isSensitive, serializer);
    sse_encode_String(self.cursorTextBefore, serializer);
    sse_encode_String(self.cursorTextAfter, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_history_page(HistoryPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.totalCount, serializer);
    sse_encode_list_stored_dictation(self.records, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_insights_snapshot(
    InsightsSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalWords, serializer);
    sse_encode_u_64(self.totalDictations, serializer);
    sse_encode_u_64(self.totalSpeechDurationMs, serializer);
    sse_encode_f_64(self.averageWordsPerMinute, serializer);
    sse_encode_u_32(self.currentStreakDays, serializer);
    sse_encode_u_32(self.longestStreakDays, serializer);
    sse_encode_u_64(self.wordsCorrected, serializer);
    sse_encode_u_64(self.dictionaryHits, serializer);
    sse_encode_u_64(self.languageEnglish, serializer);
    sse_encode_u_64(self.languageHindi, serializer);
    sse_encode_u_64(self.languageHinglish, serializer);
    sse_encode_list_app_usage(self.appUsage, serializer);
    sse_encode_u_64(self.distinctAppCount, serializer);
    sse_encode_list_prim_u_32_strict(self.dailyActivity, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_app_usage(
    List<AppUsage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_app_usage(item, serializer);
    }
  }

  @protected
  void sse_encode_list_microphone_device(
    List<MicrophoneDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_microphone_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_stored_dictation(
    List<StoredDictation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stored_dictation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_vocabulary_entry(
    List<VocabularyEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vocabulary_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_microphone_device(
    MicrophoneDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDefault, serializer);
    sse_encode_bool(self.isBuiltIn, serializer);
  }

  @protected
  void sse_encode_native_settings(
    NativeSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.writingMode, serializer);
    sse_encode_bool(self.launchAtLogin, serializer);
    sse_encode_bool(self.showInDock, serializer);
    sse_encode_bool(self.keepModelsWarm, serializer);
    sse_encode_bool(self.showSwarBar, serializer);
    sse_encode_bool(self.dictationSounds, serializer);
    sse_encode_bool(self.muteMusic, serializer);
    sse_encode_bool(self.suggestions, serializer);
    sse_encode_bool(self.announcements, serializer);
    sse_encode_bool(self.milestones, serializer);
    sse_encode_bool(self.pasteAutomatically, serializer);
    sse_encode_bool(self.restoreClipboard, serializer);
    sse_encode_bool(self.learnFromEdits, serializer);
    sse_encode_String(self.modelPath, serializer);
    sse_encode_String(self.microphoneId, serializer);
    sse_encode_String(self.shortcutKey, serializer);
    sse_encode_list_String(self.excludedApplications, serializer);
    sse_encode_String(self.enhancementProvider, serializer);
    sse_encode_String(self.providerEndpoint, serializer);
    sse_encode_String(self.providerModel, serializer);
    sse_encode_u_32(self.historyRetentionDays, serializer);
  }

  @protected
  void sse_encode_offline_model_status(
    OfflineModelStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.installed, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_String(self.modelId, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_stored_dictation(
    StoredDictation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
    sse_encode_String(self.rawText, serializer);
    sse_encode_String(self.finalText, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.writingMode, serializer);
    sse_encode_String(self.sourceApplication, serializer);
    sse_encode_u_32(self.wordCount, serializer);
    sse_encode_u_64(self.audioDurationMs, serializer);
    sse_encode_u_64(self.speechDurationMs, serializer);
    sse_encode_u_64(self.processingDurationMs, serializer);
    sse_encode_String(self.insertionStatus, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vocabulary_entry(
    VocabularyEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.spoken, serializer);
    sse_encode_String(self.written, serializer);
    sse_encode_u_32(self.useCount, serializer);
  }

  @protected
  void sse_encode_voice_style_snapshot(
    VoiceStyleSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.sampleCount, serializer);
    sse_encode_f_64(self.averageSentenceWords, serializer);
    sse_encode_f_64(self.contractionRatio, serializer);
    sse_encode_f_64(self.lowercaseStartRatio, serializer);
  }
}
